services:
  - type: web
    name: story-hive-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASS
        sync: false
      - key: FRONTEND_URL
        sync: false
